sudo: true
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "pypy"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --yes openssh-server
install:
  - pip install coveralls
  - python setup.py install
script:
  coverage run --source=executor setup.py test
after_success:
  coveralls
