sudo: true
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --yes fakeroot openssh-server
install:
  - pip install --constraint=constraints.txt --requirement=requirements-travis.txt
  - LC_ALL=C pip install .
script:
  - make check
  - make test
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
