sudo: true
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "pypy"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --yes openssh-server
install:
  - pip install coveralls
  - LC_ALL=C pip install .
script:
  - make check
  - coverage run --source=executor setup.py test
  - coverage report --fail-under=90
after_success:
  - coveralls
